config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :photos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
   mount_uploader :file_location, PhotoImageUploader
  validates_presence_of :title, :date, :description, :file_location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
 def index
   @photos = Photo.all
 end

def new
 @photo = Photo.new
end

def create
 @photo = Photo.new(photo_params[:photo])
 @photo.save

 redirect_to photos_url
end

def show
 @photo = Photo.find(params[:id])
end

def edit
 @photo = Photo.find(params[:id])
end


def update
 @photo = Photo.find(params[:id])
 @photo.update(photo_params)

 redirect_to photo_url(@photo)
end


def destroy
 @photo = Photo.find(params[:id])
 @photo.destroy

 redirect_to photos_url
end

private

def photo_params
 params.require(:photo).permit(:title, :date, :description, :file_location)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<% if @photo.errors.present?%>
  <ul>
        <% @photo.errors.each do |error, message|%>
          <li> <%= "#{error.capitalize}  #{message}" %></li>
        <% end %>
  </ul>
<% end%>
<%= form_for @photo do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title%>
  <%= f.label :date%>
  <%= f.text_field :date%>
  <%= f.label :description%>
  <%= f.text_field :description%>
  <%= f.label :file_location%>
  <%= f.file_field :file_location%>
  <%= f.submit %>

<% end %>

app/views/photos/edit.html.erb
<%= render :partial => "form"%>

app/views/photos/index.html.erb
<ul>
 <% @photos.each do |photo| %>
  <li>
    <%= photo.title %>
    <%= link_to 'Show', photo_path(photo) %>
    <%= link_to 'Edit', edit_photo_path(photo) %>
    <%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %>
  </li>
 <% end %>
</ul>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= render :partial => "form"%>

app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.date %>
<%= image_tag "/#{@photo.file_location}"%>
<%= simple_format(@photo.description) %>

<p><%= link_to 'Back to index', photos_path %></p>